# Generated by Django 3.2.9 on 2021-12-30 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tranzactie',
            fields=[
                ('id_tranzactie', models.AutoField(primary_key=True, serialize=False)),
                ('id_masina', models.CharField(max_length=20)),
                ('id_card_client', models.CharField(max_length=20)),
                ('suma_piese', models.IntegerField()),
                ('suma_manopera', models.IntegerField()),
                ('data', models.DateField()),
                ('suma_totala', models.IntegerField()),
            ],
        ),
    ]
