# Generated by Django 3.2.9 on 2021-12-30 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tranzactie_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tranzactie',
            name='id_card_client',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tranzactie',
            name='id_masina',
            field=models.IntegerField(),
        ),
    ]
