# Generated by Django 3.2.9 on 2023-03-19 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tranzactie_app', '0002_auto_20211230_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tranzactie',
            name='suma_manopera',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='tranzactie',
            name='suma_piese',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='tranzactie',
            name='suma_totala',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
