# Generated by Django 3.2.9 on 2021-12-30 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CardClient',
            fields=[
                ('id_card_client', models.AutoField(primary_key=True, serialize=False)),
                ('nume_client', models.CharField(max_length=50)),
                ('prenume_client', models.CharField(max_length=50)),
                ('CNP_client', models.CharField(max_length=50)),
                ('data_inregistrarii', models.CharField(max_length=30)),
                ('data_nasterii', models.CharField(max_length=30)),
            ],
        ),
    ]
