# Generated by Django 3.2.9 on 2021-12-30 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card_client_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardclient',
            name='data_inregistrarii',
            field=models.DateField(max_length=30),
        ),
        migrations.AlterField(
            model_name='cardclient',
            name='data_nasterii',
            field=models.DateField(max_length=30),
        ),
    ]
