# Generated by Django 3.2.9 on 2023-03-19 10:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card_client_app', '0002_auto_20211230_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardclient',
            name='CNP_client',
            field=models.CharField(max_length=13, unique=True, validators=[django.core.validators.RegexValidator(code='nomatch', message='CNP-ul nu poate avea o lungime diferita de 13', regex='^[0-9]{13}$')]),
        ),
    ]
