# Generated by Django 3.2.9 on 2021-12-30 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id_car', models.AutoField(primary_key=True, serialize=False)),
                ('model_car', models.CharField(max_length=50)),
                ('an_achizitie_car', models.DateField()),
                ('nr_km_car', models.IntegerField()),
                ('garantie_car', models.CharField(max_length=50)),
            ],
        ),
    ]
